### ISSUE TITLE
abbraviations_eng.xlsx is missing

### ISSUE THREAD

**Issue by krekiehn** [ipekdk/abbreviation-list-english#1]
Dear ipekdk,

the "abbraviations_eng.xlsx" is missing. Can you please provide the file?

Greetings krekiehn

**Comment by ipekdk** [comment]
I added them to the hub

krekiehn ***@***.***>, 18 Haz 2023 Paz, 11:59 tarihinde şunu
yazdı:

**Comment by krekiehn** [comment]
> 

Thanks a lot!
